#!/usr/bin/env bash

ROOT=$(pwd)
echo "$ROOT"

echo START ...
cd test || exit

wget --quiet https://github.com/metaplex-foundation/metaplex-program-library/archive/refs/heads/master.zip
unzip master.zip 
rm -rf rust
mkdir rust
mv -f metaplex-program-library-master/auction rust
mv -f metaplex-program-library-master/metaplex rust
mv -f metaplex-program-library-master/token-metadata rust
mv -f metaplex-program-library-master/token-vault rust
mv -f metaplex-program-library-master/Cargo.toml rust
rm -rf metaplex-program-library-master
rm master.zip

programs=(
  auction/program
  token-metadata/program
  token-vault/program
  metaplex/program
)

for prog in "${programs[@]}"; do
  echo "Building $prog"  
  cd "$ROOT/test/rust/$prog" || exit
  echo PWD: 
  pwd

  cargo build-bpf
done
