# https://github.com/marketplace/actions/auto-labeler

name: Issue and Pull Request labeler
on:
  issues:
    types: [opened, transferred, reopened]
  pull_request_target:
    types: [opened, reopened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Check Labels
      id: labeler
      uses: jimschubert/labeler-action@v2
      with:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}